"""
Django settings for DistanceCalculator project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import json
import os

from dotenv import load_dotenv

from custom_logging import create_timed_rotating_log_handler

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MICRO_SERVICE_NAME = "QtxDjangoApp"

load_dotenv(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "changeme")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", 0)))

ALLOWED_HOSTS = ["*"]

# ALLOWED_HOSTS = ["127.0.0.1"]
# ALLOWED_HOSTS_ENV = os.environ.get("DJANGO_ALLOWED_HOSTS")
# if ALLOWED_HOSTS_ENV:
#     ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(","))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "QtxDjangoApi",
]

MIDDLEWARE = [
    'middleware.RequestResponseLoggingMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "QtxDjangoApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "QtxDjangoApp.wsgi.application"

# Fetch CORS_ORIGIN_WHITELIST_URLS from environment variables
CORS_ORIGIN_WHITELIST_URLS = os.getenv("CUSTOMCONNSTR_CORS_ORIGIN_WHITELIST_URLS", "").split(",")

# Ensure all URLs are trimmed of whitespace
CORS_ORIGIN_WHITELIST = [url.strip() for url in CORS_ORIGIN_WHITELIST_URLS if url.strip()]

# Allow all origins if CORS_ORIGIN_WHITELIST is empty
CORS_ORIGIN_ALLOW_ALL = not CORS_ORIGIN_WHITELIST

CORS_ALLOW_HEADERS = [
    "access-key",
    "webpage-url",
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
with open("config.json") as config_file:
    config = json.load(config_file)

merchant_codes_table = config.get("MerchantCodesTable")

# MySQL database Configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USER_NAME"),
        "PASSWORD": os.getenv("DATABASE_USER_PWD"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/



RATE_LIMIT_MAX_REQUESTS = config.get("CUSTOMCONNSTR_RATE_LIMIT_MAX_REQUESTS")

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": f"{RATE_LIMIT_MAX_REQUESTS}/minute",  # Adjust the number of requests per day as needed
    },
}


# write logs to file and console at the same time
# ---------------------------------------------
# Define base directory and log directory
LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Ensure log directory exists
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Define log file path
LOG_FILE = 'api_logs.log'
LOG_PATH = os.path.join(LOG_DIR, LOG_FILE)

# Create an empty log file if it doesn't exist
if not os.path.exists(LOG_PATH):
    open(LOG_PATH, 'a').close()

# Get logging configuration from environment variables
LOG_MAX_BYTES = int(os.environ.get('LOG_MAX_BYTES', 2 * 1024 * 1024))  # Default 5MB
LOG_KEEP_DAYS = int(os.environ.get('LOG_KEEP_DAYS', 5))  # Default 10 Days

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'Simple_Format': {
            'format': '{asctime} [{request_id}] {levelname} {module} {process} {thread} {funcName} {name}:{lineno} {message}',
            'style': '{',
        },
    },
    'filters': {
        'request_id': {
            '()': 'custom_logging.RequestIdFilter',
        },
    },
    'handlers': {
        'custom_file': {
            '()': create_timed_rotating_log_handler,
            'filename': LOG_PATH,
            'max_bytes': LOG_MAX_BYTES,
            'keep_days': LOG_KEEP_DAYS,
            'formatter': 'Simple_Format',
            'encoding': 'utf-8',
            'filters': ['request_id'],
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'Simple_Format',
            'filters': ['request_id'],
        }
    },
    'loggers': {
        '': {
            'handlers': ['custom_file', 'console'],
            'level': f'{os.getenv("LOG_LEVEL", "INFO")}',
            'propagate': True,
        },
    },
}

# Static files
STATIC_URL = "/qtx-django/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STORAGES = {"staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"}}
